### PR TITLE
Fix usage of "cert" argument

### PR DESCRIPTION
**Pull request by sscherfke**
This looks like the remainder of your refactoring. Using the `cert` works now.

### CODE REVIEW

**Comment by andrewleech** [comment]
I'll take your word for it :-)
I'm not actively using this module anymore so don't have any particular way to test this.

**Comment by andrewleech** [comment]
Do you have any other changes you'd like to make?
Would you like this update released to pypi?

**Comment by sscherfke** [comment]
I have found nothing else so far, so a new release would be nice. Thank you for the fast merge. :)

**Comment by sscherfke** [comment]
Is [this](https://pypi.python.org/pypi/aioeasywebdav) this project on PyPI? It has 2.2.0 as recent version but you released this repo as as 1.3.0. Have I mixed something up? 🤔

**Comment by andrewleech** [comment]
Ah, yep, that's it. I thought I had a newer copy of the library other than on here... but it wasn't on my public gitlab. Totally forgot about my self hosted gitlab.
So yes, the git repo pointed to on pypi is the current code.
https://gitlab.alelec.net/corona/aioeasywebdav

**Comment by sscherfke** [comment]
I found that repo, too, but it was “harder” to fix it there than it was here on GitHub …

**Comment by andrewleech** [comment]
Hehe yeah my home gitlab server is definitely harder. 
I'm moving out to my public gitlab here: https://gitlab.com/alelec/aioeasywebdav
Already pulled in your patch. 
If you do find anything else to change don't be scared off by it being Gitlab rather than GitHub, it's basically the same but better. Much better. 

After the move from my home server the unit tests don't want to just pass though, I'll need to look at them before I can release the update. Hopefully get a chance this weekend. Once they pass all I have to do is make a git tag and Gitlab ci builds the release and sends it to pypi for me.

**Comment by sscherfke** [comment]
Very nice. I know (and love) GitLab an already have an account over there. But your private instance didn't even let me create an issue. ;-)

**Comment by sscherfke** [comment]
Is your repo on gitlab set to private? Can’t see it.

**Comment by andrewleech** [comment]
Yep, always forget to change the private-by-default setting. 
And yes, gradually moving everything off my private instance. It was never intended for collaboration... I've had it running long before there was a public hosting of Gitlab to use :-)

**Comment by andrewleech** [comment]
I've pushed an update with your patch: https://pypi.python.org/pypi/aioeasywebdav/2.3.0
  
The unit tests aren't all passing though:  
https://gitlab.com/alelec/aioeasywebdav/pipelines/13328580
https://gitlab.com/alelec/aioeasywebdav/issues/1

Hopefully this wont stop your use case.

**Comment by sscherfke** [comment]
If you could add an additional sdist archive (which makes repacking for Conda or Linux distros easier), I’d be even more happy. But thanks you very much, nonetheless!

**Comment by andrewleech** [comment]
Personally I __hate__ alternate python packaging schemes like conda or distro specific blobs as they inevitably end up conflicting with packages distributed/installed from pip/pypi ... especially now that pypi has wheels which can work everywhere.... and it's all duplication and dispersion of effort which is basically dead wasted time, time which could be better spent improving the distribution from pypi (where needed) to obsolete any need to continually duplicate distribution efforts.

But irrespective of that rant I would normally upload sdists for sure. Turns out I missed that in the gitlab ci script, it's rectified now.

**Pull request merged**
